---
version: '2'
services:
  event-processor:
    build:
      context: .
      dockerfile: .\Stock.Market.EventProcessor\Dockerfile
    image: event-processor
    container_name: event-processor
    depends_on:
    - graphql-api

  history-fetcher:
    build:
      context: .
      dockerfile: .\Stock.Market.HistoryFetcher\Dockerfile
    image: history-fetcher
    container_name: history-fetcher
    depends_on:
    - graphql-api 

  graphql-api:
    build:
      context: .
      dockerfile: .\Stock.Market.WebApi.GraphQL\Dockerfile
    image: stock-market-api
    container_name: stock-market-api
    ports:
      - "80:80"
      - "443:443"


networks:
  default:
      name: stock_market_default  